### ISSUE TITLE
[Request] pfSense and OPNsense

### ISSUE THREAD

**Issue by kaysond** [antonym/netboot.xyz#1033]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add pfSense and OPNsense images

**Describe alternatives you've considered** 

**Additional context**
Saw that VyOS is available. It would be nice to have pfsense and opnsense too!

**Comment by antonym** [comment]
Feel free to discuss here:

https://github.com/netbootxyz/netboot.xyz/discussions/926

They are based on FreeBSD which isn't very netboot friendly. If there are some reliable ways to boot with iPXE, then we would definitely consider.

**Comment by no-usernames-left** [comment]
Given that [FreeBSD is now a supported OS](https://github.com/netbootxyz/netboot.xyz#user-content-what-operating-systems-are-currently-available-on-netbootxyz), could this decision be revisited? The inclusion of OPNsense would be fantastic (and pfSense, I'm sure, for those who roll that way).

**Comment by antonym** [comment]
FreeBSD install is a little bit hacky and depends on memdisk and the mfsbsd disk image which means it only works in Legacy mode. If there are any newer or supported ways to install FreeBSD based OS that I may have missed, let me know and I can dig into it.

**Comment by no-usernames-left** [comment]
It works fine in Ventoy; perhaps their approach is worth looking at?

**Comment by Kipjr** [comment]
This might be worth considering, so only FreeBSD 13.1 or higher is required. 

https://github.com/opnsense/update/tree/master?tab=readme-ov-file#opnsense-bootstrap
https://docs.opnsense.org/manual/virtuals.html#opnsense-bootstrap
