### ISSUE TITLE
Unable to install Ubuntu 21.10

### ISSUE THREAD

**Issue by yyzh** [antonym/netboot.xyz#1037]
Hi,

Since the official version of Ubuntu 21.10 has been released, so the beta link currently used by netboot.xyz is invalid, when trying to select Ubuntu 21.10 for online install, it will show that the iso file failed (because the program tries to get the file from the link of the beta version). Please check and update the setting, thank you.

**Comment by antonym** [comment]
Yup, working on that now.

**Comment by antonym** [comment]
Latest development endpoint should have the fixes now, you can get to it via the Utilities menu. I hope to have a production release out this weekend that will include it as well.
