### ISSUE TITLE
How can I chainloader netboot.xyz from grub?

### ISSUE THREAD

**Issue by fabceolin** [antonym/netboot.xyz#1044]
**Describe the bug**

I am trying to chainloader netboot.xyz from grubnetx64 (from ubuntu 20.04) and ipxe hangs immediately after load. 
https://youtu.be/nSQV1V5cjBg
Is there any way to do this?

**To Reproduce**
git clone https://github.com/fabceolin/grubnetx64-chainloader-ipxe.git
cd grubnetx64-chainloader-ipxe
git branch netboot.xyz
packer build ltsp-server.json
.# it will  take 15 minutes. Install the generated ovf
packer build ltsp-client.json
.# Install the generated ovf
run ltsp-server using virtualbox
run ltsp-client using virtualbox

**Expected behavior**
I expected to boot netboot.xyz after grubnetx64.efi

**Comment by Kipjr** [comment]
add this to /boot/grub/grub.cfg, this works for me:

```
menuentry "iPXE Netboot.xyz" {
    insmod chain
    set root=(hd0,1)
    chainloader /iso/ipxe.efi
    boot
}
```

**Comment by fabceolin** [comment]
@Kipjr Thank you for spending time and trying to help.

I was trying to load grubnetx64 (2.04, from ubuntu 20.04) over network, and then chainloader to netboot.xyz downloading over internet, without success.

But I made an exercise using the grubnetx64 from github (2.11) generated by myself and ipxe from github (1.21) and it was possible to load ipxe capable to use the internet. So I think the grub 2.04 is the culprit.
