### ISSUE TITLE
Proxmox PXE boot dosn't work

### ISSUE THREAD

**Issue by OrZidkani** [antonym/netboot.xyz#1368]
**Describe the bug**

Proxmox PXE install getting failed, I tried to use local assets and also other iso. 

The netbooxyz through an error: "dd: error writiing '/etc/hostid' : No Space left on device
mount: mounting /dev/loop1 on /mnt/.base failed: No such file or directory
[ERROR] mount '/mnt/pve-base/squasfs' failed

**To Reproduce**
1. Go to PXE menu an try to boot Proxmox VE

**Expected behavior**
The PXE should install Proxmox, I susspect it related to ISO size and i confirm that even with ISO size who is half size (600MB) out of 1.2GB the issue perssist.
**Screenshots**
![image](https://github.com/netbootxyz/netboot.xyz/assets/31033101/7e6a06e2-77e5-4c70-8452-b35a3ccb229f)

**Additional context**
My env: 
Netbootxyz:latest - Docker container. 
PXE Client: Proxmox VM

**Comment by antonym** [comment]
Try increasing your RAM, it looks like it ran out of space to write the ISO to memory.

**Comment by GlitchWitch** [comment]
I'm running into this same issue on a dedicated server with an Intel Xeon-E 2136 and 64 GB of ECC 2666 ram. It seems #1109 had the same issue.

Other netboot images work, however proxmox does not.


@antonym Any advice to help troubleshoot would be appreicated.

**Comment by OrZidkani** [comment]
@antonym Thanks!
Increase the ram solved it!
